apiVersion : apps/v1
kind : Deployment
metadata:
  name : my-web-deployment
  labels:
    app : my-k8s-app
spec:
  selector:
    matchLabels:
      project : kgb
  template:
    metadata:
      lables:
        project : kgb
    spec:
      containers:
        - name: kgb-web
          image: repo_name/image_name:version1
          ports:
            - containerPort:80