apiVersion: networking.k8s.io/v1
kind : Ingress
metadata :
  name : Ingress-hosts

spec :
  rules :
  - host : www.test.net
    http :
      paths :
        - backend :
            serviceName : main
            servicePort : 80

  - host : web1.test.net
    http :
      paths :
        - backend :
            serviceName : web1
            servicePort : 80
  
  - host : web2.test.net
    http :
      paths :
        - backend :
            serviceName : web2
            servicePort : 80

  - host : tomcat.test.net
    http :
      paths :
        - backend :
            serviceName : tomcat
            servicePort : 8080